CREATE DATABASE LIBRARY_MANAGEMENT_SYSTEM;
USE LIBRARY_MANAGEMENT_SYSTEM;
CREATE TABLE BOOKS
(
	ID INT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    AUTHOR_NAME VARCHAR(50) NOT NULL,
    CATEGORY VARCHAR(50),
    ISBN VARCHAR(30) NOT NULL,
    PUBLISHED_YEAR VARCHAR(15),
    LANGUAGE VARCHAR(15),
    COOPIES_TOTAL INT NOT NULL,
    COOPIES_AVAILABLE INT NOT NULL,
    SHELF VARCHAR(50),
    STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT PK_BOOKS PRIMARY KEY (ID)
);